// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkoutLogger.Data;

#nullable disable

namespace WorkoutLogger.Migrations
{
    [DbContext(typeof(WorkoutsDb))]
    [Migration("20260616190624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkoutLogger.Models.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WorkoutLogger.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MuscleGroup = "Chest",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            MuscleGroup = "Shoulders",
                            Name = "Overhead Shoulder Press"
                        },
                        new
                        {
                            Id = 3,
                            MuscleGroup = "Back",
                            Name = "Pull Ups"
                        },
                        new
                        {
                            Id = 4,
                            MuscleGroup = "Back",
                            Name = "Barbell Rows"
                        },
                        new
                        {
                            Id = 5,
                            MuscleGroup = "Quadriceps",
                            Name = "Barbell Squat"
                        },
                        new
                        {
                            Id = 6,
                            MuscleGroup = "Hamstrings",
                            Name = "Romanian Deadlift"
                        });
                });

            modelBuilder.Entity("WorkoutLogger.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentDay")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Workouts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentDay = 0,
                            DateTime = new DateTimeOffset(new DateTime(2026, 1, 5, 17, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Push Day"
                        },
                        new
                        {
                            Id = 2,
                            CurrentDay = 2,
                            DateTime = new DateTimeOffset(new DateTime(2026, 1, 7, 18, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Pull Day"
                        },
                        new
                        {
                            Id = 3,
                            CurrentDay = 4,
                            DateTime = new DateTimeOffset(new DateTime(2026, 1, 9, 17, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Notes = "Leg Day"
                        });
                });

            modelBuilder.Entity("WorkoutLogger.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("WorkoutExercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reps_Range", "\"Reps\" >= 0 AND \"Reps\" <= 100");

                            t.HasCheckConstraint("CK_Sets_Range", "\"Sets\" >= 0 AND \"Sets\" <= 10");

                            t.HasCheckConstraint("CK_WeightsKg_Range", "\"WeightKg\" >= 0 AND \"WeightKg\" <= 1000");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            Reps = 10,
                            Sets = 4,
                            WeightKg = 90.0,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 2,
                            Reps = 12,
                            Sets = 4,
                            WeightKg = 25.0,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 3,
                            Reps = 5,
                            Sets = 3,
                            WeightKg = 115.0,
                            WorkoutId = 2
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 4,
                            Reps = 5,
                            Sets = 5,
                            WeightKg = 85.0,
                            WorkoutId = 2
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 5,
                            Reps = 8,
                            Sets = 6,
                            WeightKg = 120.0,
                            WorkoutId = 3
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 6,
                            Reps = 6,
                            Sets = 5,
                            WeightKg = 140.0,
                            WorkoutId = 3
                        });
                });

            modelBuilder.Entity("WorkoutLogger.Models.WorkoutExercise", b =>
                {
                    b.HasOne("WorkoutLogger.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutLogger.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutLogger.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("WorkoutLogger.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
